export const medical = {
    // Tabs
    "tab_vitals": "Vitals & Triage",
    "tab_notes": "Exam & Diagnosis",
    "tab_rx": "Prescription",
    "tab_services": "Services & Billing",

    // Actions
    "save_draft": "Save Draft",
    "finalize_visit": "Finalize Visit",
    "print_rx": "Print Prescription",
    "add": "Add",
    "remove": "Remove",

    // Vitals
    "vitals_title": "Vital Signs",
    "blood_pressure": "Blood Pressure",
    "heart_rate": "Heart Rate (BPM)",
    "temp": "Temp (°C)",
    "weight": "Weight (kg)",
    "oxygen": "O2 Saturation (%)",
    "triage_notes": "Chief Complaint / Triage Notes",
    "triage_placeholder": "Patient complains of...",

    // Exam & Diagnosis
    "exam_findings": "Examination Findings",
    "exam_placeholder": "Chest clear, heart sounds normal...",
    "diagnosis": "Diagnosis (ICD-10)",
    "diagnosis_placeholder": "e.g. Essential Hypertension",
    "plan": "Plan & Follow-up",
    "plan_placeholder": "Rest for 3 days, return if fever persists...",

    // Prescription
    "rx_builder": "Prescription Builder",
    "medication": "Medication",
    "search_drug": "Search drug...",
    "dosage": "Dosage",
    "frequency": "Frequency",
    "duration": "Duration",
    "no_meds": "No medications added yet.",
    "rx_header_title": "Al-Fath Clinic",
    "rx_header_subtitle": "Downtown Branch • 123 Main St, Cairo",
    "rx_doc_signature": "Doctor's Signature",
    "generated_by": "Generated by Al-Fath System",

    // Services
    "add_services": "Add Services / Procedures",
    "invoice_title": "Current Visit Invoice",
    "total": "Total",
    "item": "Item",
    "qty": "Qty",
    "price": "Price",
    "base_fee": "Base Fee",

    // Patient Info
    "patient_history": "Patient History",
    "previous_visits": "Previous Visits",
    "allergies": "Allergies",
};
