import {
  addBillingItemViaApi,
  clearAuthToken,
  closeDoctorPayrollPeriod,
  consumeAccessLinkViaApi,
  createAccessLinkViaApi,
  createAppointmentViaApi,
  createBranchViaApi,
  createDoctorViaApi,
  createPatientViaApi,
  deleteBranchViaApi,
  exportDoctorPayrollReportCsvFromApi,
  exportFinancialReportCsvFromApi,
  getAppointmentsFromApi,
  getAvailableSlotsBulkFromApi,
  getBranchSettingsFromApi,
  getBranchesFromApi,
  getClinicSettingsFromApi,
  getCurrentUser,
  getDelayInsightViaApi,
  getDepartmentsFromApi,
  getDoctorPayrollReportFromApi,
  getDoctorProfileFromApi,
  getDoctorsFromApi,
  getFinancialReportFromApi,
  getMedicalEncounterFromApi,
  getPatientAuditTimelineFromApi,
  getPatientsFromApi,
  getReconciliationReportFromApi,
  loginWithApi,
  previewShiftAppointmentsViaApi,
  processAppointmentPaymentViaApi,
  removeBillingItemViaApi,
  resetBranchSettingsViaApi,
  saveMedicalEncounterViaApi,
  settleDoctorPayrollPeriod,
  shiftAppointmentsViaApi,
  startVisitNowViaApi,
  updateAppointmentStatusViaApi,
  updateBranchSettingsViaApi,
  updateBranchViaApi,
  updateClinicSettingsViaApi,
  updateDoctorAdvancedModeFromApi,
  updateDoctorProfileFromApi,
  updateDoctorViaApi,
  lookupPatientsByPhoneFromApi,
} from '../../api';
import type { Repositories } from '../contracts';

export const apiRepositories: Repositories = {
  auth: {
    login: loginWithApi,
    getCurrentUser,
    clearAuthToken,
    consumeAccessLink: consumeAccessLinkViaApi,
    createAccessLink: createAccessLinkViaApi,
  },
  branches: {
    getBranches: getBranchesFromApi,
    createBranch: createBranchViaApi,
    updateBranch: updateBranchViaApi,
    deleteBranch: deleteBranchViaApi,
    getBranchSettings: getBranchSettingsFromApi,
    updateBranchSettings: updateBranchSettingsViaApi,
    resetBranchSettings: resetBranchSettingsViaApi,
  },
  doctors: {
    getDoctors: getDoctorsFromApi,
    createDoctor: createDoctorViaApi,
    updateDoctor: updateDoctorViaApi,
    getDepartments: getDepartmentsFromApi,
    getDoctorProfile: getDoctorProfileFromApi,
    updateDoctorProfile: updateDoctorProfileFromApi,
    updateDoctorAdvancedMode: updateDoctorAdvancedModeFromApi,
  },
  appointments: {
    getPatients: getPatientsFromApi,
    getAppointments: getAppointmentsFromApi,
    createPatient: createPatientViaApi,
    lookupPatientsByPhone: lookupPatientsByPhoneFromApi,
    getAvailableSlotsBulk: getAvailableSlotsBulkFromApi,
    createAppointment: createAppointmentViaApi,
    startVisitNow: startVisitNowViaApi,
    updateAppointmentStatus: updateAppointmentStatusViaApi,
    addBillingItem: addBillingItemViaApi,
    processAppointmentPayment: processAppointmentPaymentViaApi,
    removeBillingItem: removeBillingItemViaApi,
    getMedicalEncounter: getMedicalEncounterFromApi,
    saveMedicalEncounter: saveMedicalEncounterViaApi,
    getDelayInsight: getDelayInsightViaApi,
    previewShiftAppointments: previewShiftAppointmentsViaApi,
    shiftAppointments: shiftAppointmentsViaApi,
    getPatientAuditTimeline: getPatientAuditTimelineFromApi,
  },
  settings: {
    getClinicSettings: getClinicSettingsFromApi,
    updateClinicSettings: updateClinicSettingsViaApi,
  },
  reports: {
    getFinancialReport: getFinancialReportFromApi,
    exportFinancialReportCsv: exportFinancialReportCsvFromApi,
    getReconciliationReport: getReconciliationReportFromApi,
    getDoctorPayrollReport: getDoctorPayrollReportFromApi,
    exportDoctorPayrollReportCsv: exportDoctorPayrollReportCsvFromApi,
    closeDoctorPayrollPeriod,
    settleDoctorPayrollPeriod,
  },
};
